name: vitpool
channels:
  - defaults
dependencies:
  - _libgcc_mutex==0.1=conda_forge
  - _openmp_mutex==4.5=2_gnu
  - aiohappyeyeballs==2.4.3=py311h06a4308_0
  - aiohttp==3.10.5=py311h5eee18b_0
  - aiosignal==1.2.0=pyhd3eb1b0_0
  - attrs==24.2.0=py311h06a4308_0
  - blas==1.0=mkl
  - brotli-bin==1.1.0=hb9d3cd8_2
  - brotli-python==1.0.9=py311h6a678d5_8
  - brotli==1.1.0=hb9d3cd8_2
  - bzip2==1.0.8=h5eee18b_6
  - ca-certificates==2026.1.4
  - cairo==1.18.0=h3faef2a_0
  - certifi==2026.1.4
  - chardet==5.2.0=py311h38be061_2
  - charset-normalizer==3.3.2=pyhd3eb1b0_0
  - contourpy==1.3.1=py311hd18a35c_0
  - cuda-cudart==12.1.105=0
  - cuda-cupti==12.1.105=0
  - cuda-libraries==12.1.0=0
  - cuda-nvrtc==12.1.105=0
  - cuda-nvtx==12.1.105=0
  - cuda-opencl==12.4.127=0
  - cuda-runtime==12.1.0=0
  - cuda-version==11.8=hcce14f8_3
  - cudatoolkit==11.8.0=h6a678d5_0
  - cycler==0.12.1=pyhd8ed1ab_1
  - expat==2.6.4=h5888daf_0
  - ffmpeg==4.3=hf484d3e_0
  - filelock==3.13.1=py311h06a4308_0
  - font-ttf-dejavu-sans-mono==2.37=hab24e00_0
  - font-ttf-inconsolata==3.000=h77eed37_0
  - font-ttf-source-code-pro==2.038=h77eed37_0
  - font-ttf-ubuntu==0.83=h77eed37_3
  - fontconfig==2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem==1=0
  - fonts-conda-forge==1=0
  - fonttools==4.55.1=py311h2dc5d0c_0
  - freetype-py==2.3.0=pyhd8ed1ab_0
  - freetype==2.12.1=h4a9f257_0
  - frozenlist==1.5.0=py311h5eee18b_0
  - fsspec==2024.10.0=pyhff2d567_0
  - giflib==5.2.2=h5eee18b_0
  - gmp==6.2.1=h295c915_3
  - gmpy2==2.1.2=py311hc9b5ff0_0
  - gnutls==3.6.15=he1e5248_0
  - greenlet==3.1.1=py311hfdbb021_0
  - icu==73.2=h59595ed_0
  - idna==3.7=py311h06a4308_0
  - intel-openmp==2023.1.0=hdb19cb5_46306
  - jinja2==3.1.4=py311h06a4308_1
  - jpeg==9e=h5eee18b_3
  - keyutils==1.6.1=h166bdaf_0
  - kiwisolver==1.4.7=py311hd18a35c_0
  - krb5==1.21.3=h659f571_0
  - lame==3.100=h7b6447c_0
  - lcms2==2.12=h3be6417_0
  - ld_impl_linux-64==2.40=h12ee557_0
  - lerc==3.0=h295c915_0
  - libboost-python==1.84.0=py311h5b7b71f_6
  - libboost==1.84.0=hba137d9_3
  - libbrotlicommon==1.1.0=hb9d3cd8_2
  - libbrotlidec==1.1.0=hb9d3cd8_2
  - libbrotlienc==1.1.0=hb9d3cd8_2
  - libcublas==12.1.0.26=0
  - libcufft==11.0.2.4=0
  - libcufile==1.9.1.3=0
  - libcurand==10.3.5.147=0
  - libcusolver==11.4.4.55=0
  - libcusparse==12.0.2.55=0
  - libdeflate==1.17=h5eee18b_1
  - libedit==3.1.20191231=he28a2e2_2
  - libexpat==2.6.4=h5888daf_0
  - libffi==3.4.4=h6a678d5_1
  - libgcc-ng==14.2.0=h69a702a_1
  - libgcc==14.2.0=h77fa898_1
  - libgfortran-ng==11.2.0=h00389a5_1
  - libgfortran5==11.2.0=h1234567_1
  - libglib==2.78.4=hdc74915_0
  - libgomp==14.2.0=h77fa898_1
  - libiconv==1.16=h5eee18b_3
  - libidn2==2.3.4=h5eee18b_0
  - libjpeg-turbo==2.0.0=h9bf148f_0
  - libnpp==12.0.2.50=0
  - libnsl==2.0.1=hd590300_0
  - libnvjitlink==12.1.105=0
  - libnvjpeg==12.1.1.14=0
  - libpng==1.6.39=h5eee18b_0
  - libpq==16.6=h035377e_1
  - librdkit==2024.03.6=h04b5189_0
  - libsqlite==3.46.0=hde9e2c9_0
  - libstdcxx-ng==14.2.0=h4852527_1
  - libstdcxx==14.2.0=hc0a3c3a_1
  - libtasn1==4.19.0=h5eee18b_0
  - libtiff==4.5.1=h6a678d5_0
  - libunistring==0.9.10=h27cfd23_0
  - libuuid==2.38.1=h0b41bf4_0
  - libwebp-base==1.3.2=h5eee18b_1
  - libwebp==1.3.2=h11a3e52_0
  - libxcb==1.15=h0b41bf4_0
  - libxcrypt==4.4.36=hd590300_1
  - libxml2==2.13.5=hfdd30dd_0
  - libzlib==1.2.13=h4ab18f5_6
  - llvm-openmp==14.0.6=h9e868ea_0
  - lz4-c==1.9.4=h6a678d5_1
  - markupsafe==2.1.3=py311h5eee18b_0
  - matplotlib-base==3.9.3=py311h2b939e6_0
  - mkl-service==2.4.0=py311h5eee18b_1
  - mkl==2023.1.0=h213fc3f_46344
  - mkl_fft==1.3.11=py311h5eee18b_0
  - mkl_random==1.2.8=py311ha02d727_0
  - mpc==1.1.0=h10f8cd9_1
  - mpfr==4.0.2=hb69a4c5_1
  - mpmath==1.3.0=py311h06a4308_0
  - multidict==6.1.0=py311h5eee18b_0
  - munkres==1.1.4=pyh9f0ad1d_0
  - ncurses==6.4=h6a678d5_0
  - nettle==3.7.3=hbbd107a_1
  - networkx==3.2.1=py311h06a4308_0
  - numpy-base==1.26.4=py311hf175353_0
  - numpy==1.26.4=py311h08b1b3b_0
  - openbabel==3.1.1=py311h8b422cb_9
  - openh264==2.1.1=h4ff587b_0
  - openjpeg==2.5.2=he7f1fd0_0
  - openssl==3.6.1
  - packaging==24.2=pyhd8ed1ab_2
  - pandas==2.2.3=py311h7db5c69_1
  - pcre2==10.42=hcad00b1_0
  - pillow==11.0.0=py311hfdbf927_0
  - pip==24.2=py311h06a4308_0
  - pixman==0.43.2=h59595ed_0
  - propcache==0.2.0=py311h5eee18b_0
  - psutil==5.9.0=py311h5eee18b_0
  - pthread-stubs==0.4=hb9d3cd8_1002
  - pycairo==1.27.0=py311h124c5f0_0
  - pyg==2.6.1=py311_torch_2.4.0_cu121
  - pyparsing==3.2.0=py311h06a4308_0
  - pysocks==1.7.1=py311h06a4308_0
  - python-dateutil==2.9.0.post0=pyhff2d567_1
  - python-tzdata==2024.2=pyhd8ed1ab_1
  - python==3.11.8=hab00c5b_0_cpython
  - python_abi==3.11=5_cp311
  - pytorch-cuda==12.1=ha16c6d3_6
  - pytorch-mutex==1.0=cuda
  - pytorch==2.4.1=py3.11_cuda12.1_cudnn9.1.0_0
  - pytz==2024.1=pyhd8ed1ab_0
  - pyyaml==6.0.2=py311h5eee18b_0
  - qhull==2020.2=h434a139_5
  - rdkit==2024.03.6=py311ha09a670_0
  - readline==8.2=h5eee18b_0
  - reportlab==4.2.5=py311h9ecbd09_0
  - requests==2.32.3=py311h06a4308_1
  - rlpycairo==0.2.0=pyhd8ed1ab_0
  - scipy==1.14.1=py311h08b1b3b_0
  - setuptools==75.1.0=py311h06a4308_0
  - six==1.17.0=pyhd8ed1ab_0
  - sqlalchemy==2.0.36=py311h9ecbd09_0
  - sqlite==3.45.3=h5eee18b_0
  - sympy==1.13.2=py311h06a4308_0
  - tbb==2021.8.0=hdb19cb5_0
  - tk==8.6.14=h39e8969_0
  - torchaudio==2.4.1=py311_cu121
  - torchtriton==3.0.0=py311
  - torchvision==0.15.2=cuda118py311h4cc2eb7_0
  - tqdm==4.66.5=py311h92b7b1e_0
  - tzdata==2024b=h04d1e81_0
  - unicodedata2==15.1.0=py311h9ecbd09_1
  - urllib3==2.2.3=py311h06a4308_0
  - wheel==0.44.0=py311h06a4308_0
  - xorg-kbproto==1.0.7=hb9d3cd8_1003
  - xorg-libice==1.1.1=hb9d3cd8_1
  - xorg-libsm==1.2.4=he73a12e_1
  - xorg-libx11==1.8.9=h8ee46fc_0
  - xorg-libxau==1.0.11=hb9d3cd8_1
  - xorg-libxdmcp==1.1.5=hb9d3cd8_0
  - xorg-libxext==1.3.4=h0b41bf4_2
  - xorg-libxrender==0.9.11=hd590300_0
  - xorg-renderproto==0.11.1=hb9d3cd8_1003
  - xorg-xextproto==7.3.0=hb9d3cd8_1004
  - xorg-xproto==7.0.31=hb9d3cd8_1008
  - xz==5.4.6=h5eee18b_1
  - yaml==0.2.5=h7b6447c_0
  - yarl==1.18.0=py311h5eee18b_0
  - zlib==1.2.13=h4ab18f5_6
  - zstd==1.5.6=hc292b87_0
  - ipykernel
  - cuda-toolkit
prefix: /home/liux31/miniconda3/envs/vitpool
